// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Devices.Communication
	{
		/// <summary>Contains information about a communications device.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winbase/ns-winbase-comstat">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct COMSTAT
		{
			internal uint _bitfield;
			/// <summary>
			/// <para>The number of bytes received by the serial provider but not yet read by a <a href="https://docs.microsoft.com/windows/desktop/api/fileapi/nf-fileapi-readfile">ReadFile</a> operation.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winbase/ns-winbase-comstat#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint cbInQue;
			/// <summary>The number of bytes of user data remaining to be transmitted for all write operations. This value will be zero for a nonoverlapped write.</summary>
			internal uint cbOutQue;
		}
	}
}
