// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal enum DEVICEFAMILYINFOENUM : uint
		{
			DEVICEFAMILYINFOENUM_UAP = 0U,
			DEVICEFAMILYINFOENUM_WINDOWS_8X = 1U,
			DEVICEFAMILYINFOENUM_WINDOWS_PHONE_8X = 2U,
			DEVICEFAMILYINFOENUM_DESKTOP = 3U,
			DEVICEFAMILYINFOENUM_MOBILE = 4U,
			DEVICEFAMILYINFOENUM_XBOX = 5U,
			DEVICEFAMILYINFOENUM_TEAM = 6U,
			DEVICEFAMILYINFOENUM_IOT = 7U,
			DEVICEFAMILYINFOENUM_IOT_HEADLESS = 8U,
			DEVICEFAMILYINFOENUM_SERVER = 9U,
			DEVICEFAMILYINFOENUM_HOLOGRAPHIC = 10U,
			DEVICEFAMILYINFOENUM_XBOXSRA = 11U,
			DEVICEFAMILYINFOENUM_XBOXERA = 12U,
			DEVICEFAMILYINFOENUM_SERVER_NANO = 13U,
			DEVICEFAMILYINFOENUM_8828080 = 14U,
			DEVICEFAMILYINFOENUM_7067329 = 15U,
			DEVICEFAMILYINFOENUM_WINDOWS_CORE = 16U,
			DEVICEFAMILYINFOENUM_WINDOWS_CORE_HEADLESS = 17U,
			DEVICEFAMILYINFOENUM_MAX = 17U,
		}
	}
}
