// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		[Flags]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal enum VER_FLAGS : uint
		{
			VER_MINORVERSION = 0x00000001,
			VER_MAJORVERSION = 0x00000002,
			VER_BUILDNUMBER = 0x00000004,
			VER_PLATFORMID = 0x00000008,
			VER_SERVICEPACKMINOR = 0x00000010,
			VER_SERVICEPACKMAJOR = 0x00000020,
			VER_SUITENAME = 0x00000040,
			VER_PRODUCT_TYPE = 0x00000080,
		}
	}
}
