// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.WindowsAndMessaging
	{
		/// <summary>Contains status information for the application-switching (ALT+TAB) window.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct ALTTABINFO
		{
			/// <summary>
			/// <para>Type: <b>DWORD</b> The size, in bytes, of the structure. The caller must set this to <c>sizeof(ALTTABINFO)</c>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint cbSize;
			/// <summary>
			/// <para>Type: <b>int</b> The number of items in the window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int cItems;
			/// <summary>
			/// <para>Type: <b>int</b> The number of columns in the window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int cColumns;
			/// <summary>
			/// <para>Type: <b>int</b> The number of rows in the window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int cRows;
			/// <summary>
			/// <para>Type: <b>int</b> The column of the item that has the focus.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int iColFocus;
			/// <summary>
			/// <para>Type: <b>int</b> The row of the item that has the focus.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int iRowFocus;
			/// <summary>
			/// <para>Type: <b>int</b> The width of each icon in the application-switching window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int cxItem;
			/// <summary>
			/// <para>Type: <b>int</b> The height of each icon in the application-switching window.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int cyItem;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/previous-versions/dd162805(v=vs.85)">POINT</a></b> The top-left corner of the first icon.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-alttabinfo#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal global::System.Drawing.Point ptStart;
		}
	}
}
