// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.ProcessStatus
	{
		/// <summary>Contains information about a pagefile.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//psapi/ns-psapi-enum_page_file_information">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct ENUM_PAGE_FILE_INFORMATION
		{
			/// <summary>The size of this structure, in bytes.</summary>
			internal uint cb;
			/// <summary>This member is reserved.</summary>
			internal uint Reserved;
			/// <summary>The total size of the pagefile, in pages.</summary>
			internal nuint TotalSize;
			/// <summary>The current pagefile usage, in pages.</summary>
			internal nuint TotalInUse;
			/// <summary>The peak pagefile usage, in pages.</summary>
			internal nuint PeakUsage;
		}
	}
}
