// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		/// <summary>Describes the relationship between the specified processor set. This structure is used with the GetLogicalProcessorInformation function.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-system_logical_processor_information">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct SYSTEM_LOGICAL_PROCESSOR_INFORMATION
		{
			/// <summary>
			/// <para>The processor mask  identifying the processors described by this structure. A processor mask is a bit vector in which each set bit represents an active processor in the relationship. At least one bit will be set. On a system with more than 64 processors, the processor mask identifies processors in a single <a href="https://docs.microsoft.com/windows/desktop/ProcThread/processor-groups">processor group</a>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-system_logical_processor_information#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal nuint ProcessorMask;
			/// <summary>
			/// <para>The relationship between the processors identified by the value of the <b>ProcessorMask</b> member. This member can be one of the following <a href="https://docs.microsoft.com/windows/desktop/api/winnt/ne-winnt-logical_processor_relationship">LOGICAL_PROCESSOR_RELATIONSHIP</a> values. </para>
			/// <para>This doc was truncated.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-system_logical_processor_information#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.System.SystemInformation.LOGICAL_PROCESSOR_RELATIONSHIP Relationship;
			internal winmdroot.System.SystemInformation.SYSTEM_LOGICAL_PROCESSOR_INFORMATION._Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.SYSTEM_LOGICAL_PROCESSOR_INFORMATION._Anonymous_e__Union._ProcessorCore_e__Struct ProcessorCore;
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.SYSTEM_LOGICAL_PROCESSOR_INFORMATION._Anonymous_e__Union._NumaNode_e__Struct NumaNode;
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.CACHE_DESCRIPTOR Cache;
				[FieldOffset(0)]
				internal winmdroot.__ulong_2 Reserved;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _ProcessorCore_e__Struct
				{
					internal byte Flags;
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _NumaNode_e__Struct
				{
					internal uint NodeNumber;
				}
			}
		}
	}
}
