// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
	internal static partial class InlineArrayIndexerExtensions
	{
		internal static ReadOnlySpan<char> SliceAtNull(this ReadOnlySpan<char>value)
		{
			int length = value.IndexOf('\0');
			return length < 0 ? value : value.Slice(0, length);
		}

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_32 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_80 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_512 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_260 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_256 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly uint ReadOnlyItemRef(this in winmdroot.__uint_3 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_128 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly ulong ReadOnlyItemRef(this in winmdroot.__ulong_2 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_20 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly ushort ReadOnlyItemRef(this in winmdroot.__ushort_3 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_18 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_38 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_1 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_14 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_16 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_2 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_12 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_8 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_50 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_30 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_50 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_80 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_30 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_1 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly float ReadOnlyItemRef(this in winmdroot.__float_16 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly char ReadOnlyItemRef(this in winmdroot.__char_520 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly uint ReadOnlyItemRef(this in winmdroot.__uint_6 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_32 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly ushort ReadOnlyItemRef(this in winmdroot.__ushort_8 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_6 @this, int index) => ref @this.Value[index];

		internal static unsafe ref readonly byte ReadOnlyItemRef(this in winmdroot.__byte_3 @this, int index) => ref @this.Value[index];
	}
}
