// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.IO
	{
		/// <summary>Contains the information returned by a call to the GetQueuedCompletionStatusEx function.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//minwinbase/ns-minwinbase-overlapped_entry">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct OVERLAPPED_ENTRY
		{
			/// <summary>
			/// <para>Receives the completion key value associated with the file handle whose I/O operation has completed. A completion key is a per-file key that is specified in a call to <a href="https://docs.microsoft.com/windows/desktop/FileIO/createiocompletionport">CreateIoCompletionPort</a>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//minwinbase/ns-minwinbase-overlapped_entry#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal nuint lpCompletionKey;
			/// <summary>
			/// <para>Receives the address of the <a href="https://docs.microsoft.com/windows/desktop/api/minwinbase/ns-minwinbase-overlapped">OVERLAPPED</a> structure that was specified when the completed I/O operation was started.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//minwinbase/ns-minwinbase-overlapped_entry#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal unsafe global::System.Threading.NativeOverlapped* lpOverlapped;
			/// <summary>Reserved.</summary>
			internal nuint Internal;
			/// <summary>Receives the number of bytes transferred during the I/O operation that has completed.</summary>
			internal uint dwNumberOfBytesTransferred;
		}
	}
}
