// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Networking.WinSock
	{
		/// <summary>The in_addr structure represents an IPv4 Internet address.</summary>
		/// <remarks>
		/// <para>The <b>in_addr</b> structure is used with IPv4 addresses. The <b>in_addr</b> structure is the IPv4 equivalent of the IPv6-based <a href="https://docs.microsoft.com/previous-versions/windows/desktop/legacy/ms738560(v=vs.85)">in6_addr</a> structure. <div class="alert"><b>Note</b>  The <b>IN_ADDR</b>, <b>PIN_ADDR</b>, and  <b>LPIN_ADDR</b> derived structures are only defined on the Windows SDK released with Windows Vista and later. The <b>IN_ADDR</b>, <b>PIN_ADDR</b>, and  <b>LPIN_ADDR</b> derived structures are defined in the <i>Inaddr.h</i> header file. On earlier versions of the Windows SDK, variables of this type should be declared as <b>struct in_addr</b>. </div> <div> </div></para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winsock2/ns-winsock2-in_addr#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct IN_ADDR
		{
			/// <summary></summary>
			internal winmdroot.Networking.WinSock.IN_ADDR._S_un_e__Union S_un;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _S_un_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.Networking.WinSock.IN_ADDR._S_un_e__Union._S_un_b_e__Struct S_un_b;
				[FieldOffset(0)]
				internal winmdroot.Networking.WinSock.IN_ADDR._S_un_e__Union._S_un_w_e__Struct S_un_w;
				[FieldOffset(0)]
				internal uint S_addr;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _S_un_b_e__Struct
				{
					internal byte s_b1;
					internal byte s_b2;
					internal byte s_b3;
					internal byte s_b4;
				}

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _S_un_w_e__Struct
				{
					internal ushort s_w1;
					internal ushort s_w2;
				}
			}
		}
	}
}
