// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		internal partial struct __GROUP_AFFINITY_1
		{
			private const int SpanLength = 1;

			/// <summary>The length of the inline array.</summary>
			internal readonly int Length => SpanLength;
			internal winmdroot.System.SystemInformation.GROUP_AFFINITY _0;

			/// <summary>
			/// Gets this inline array as a span.
			/// </summary>
			/// <remarks>
			/// ⚠ Important ⚠: When this struct is on the stack, do not let the returned span outlive the stack frame that defines it.
			/// </remarks>
			[UnscopedRef]
			internal unsafe Span<winmdroot.System.SystemInformation.GROUP_AFFINITY> AsSpan() => MemoryMarshal.CreateSpan(ref _0, SpanLength);

			/// <summary>
			/// Gets this inline array as a span.
			/// </summary>
			/// <remarks>
			/// ⚠ Important ⚠: When this struct is on the stack, do not let the returned span outlive the stack frame that defines it.
			/// </remarks>
			[UnscopedRef]
			internal unsafe readonly ReadOnlySpan<winmdroot.System.SystemInformation.GROUP_AFFINITY> AsReadOnlySpan() => MemoryMarshal.CreateReadOnlySpan(ref Unsafe.AsRef(_0), SpanLength);
			public static implicit operator __GROUP_AFFINITY_1(ReadOnlySpan<winmdroot.System.SystemInformation.GROUP_AFFINITY> value)
			{
				Unsafe.SkipInit(out __GROUP_AFFINITY_1 result);
				value.CopyTo(result.AsSpan());
				int initLength = value.Length;
				result.AsSpan().Slice(initLength, SpanLength - initLength).Clear();
				return result;
			}
		}
	}
}
