// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Input.KeyboardAndMouse
	{
		/// <summary>Contains information about the mouse's location in screen coordinates.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-mousemovepoint">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct MOUSEMOVEPOINT
		{
			/// <summary>
			/// <para>Type: <b>int</b> The x-coordinate of the mouse.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-mousemovepoint#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int x;
			/// <summary>
			/// <para>Type: <b>int</b> The y-coordinate of the mouse.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-mousemovepoint#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal int y;
			/// <summary>
			/// <para>Type: <b>DWORD</b> The time stamp of the mouse coordinate.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-mousemovepoint#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint time;
			/// <summary>
			/// <para>Type: <b>ULONG_PTR</b> Additional information associated with this coordinate.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-mousemovepoint#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal nuint dwExtraInfo;
		}
	}
}
