// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Devices.Display
	{
		/// <summary>The DISPLAYCONFIG_ROTATION enumeration specifies the clockwise rotation of the display.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wingdi/ne-wingdi-displayconfig_rotation">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal enum DISPLAYCONFIG_ROTATION
		{
			/// <summary>Indicates that rotation is 0 degrees—landscape mode.</summary>
			DISPLAYCONFIG_ROTATION_IDENTITY = 1,
			/// <summary>Indicates that rotation is 90 degrees clockwise—portrait mode.</summary>
			DISPLAYCONFIG_ROTATION_ROTATE90 = 2,
			/// <summary>Indicates that rotation is 180 degrees clockwise—inverted landscape mode.</summary>
			DISPLAYCONFIG_ROTATION_ROTATE180 = 3,
			/// <summary>Indicates that rotation is 270 degrees clockwise—inverted portrait mode.</summary>
			DISPLAYCONFIG_ROTATION_ROTATE270 = 4,
			/// <summary>Forces this enumeration to compile to 32 bits in size. Without this value, some compilers would allow this enumeration to compile to a size other than 32 bits. You should not use this value.</summary>
			DISPLAYCONFIG_ROTATION_FORCE_UINT32 = -1,
		}
	}
}
