// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		/// <summary>Represents information about a NUMA node in a processor group. This structure is used with the GetLogicalProcessorInformationEx function.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-numa_node_relationship">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct NUMA_NODE_RELATIONSHIP
		{
			/// <summary>The number of the NUMA node.</summary>
			internal uint NodeNumber;
			/// <summary>This member is reserved.</summary>
			internal winmdroot.__byte_18 Reserved;
			/// <summary>The number of groups included in the *GroupMasks* array. This field was introduced in TBD Release Iron. On earlier versions, this value is always 0.</summary>
			internal ushort GroupCount;
			internal winmdroot.System.SystemInformation.NUMA_NODE_RELATIONSHIP._Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.GROUP_AFFINITY GroupMask;
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.__GROUP_AFFINITY_1 GroupMasks;
			}
		}
	}
}
