// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Networking.WinSock
	{
		/// <summary>The IN6_ADDR structure specifies an IPv6 transport address.</summary>
		/// <remarks>
		/// <para>All members of the IN6_ADDR structure must be specified in network-byte-order (big-endian).</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//in6addr/ns-in6addr-in6_addr#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct IN6_ADDR
		{
			/// <summary>
			/// <para>A union that contains the following different representations of the IPv6 transport address:</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//in6addr/ns-in6addr-in6_addr#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Networking.WinSock.IN6_ADDR._u_e__Union u;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _u_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.__byte_16 Byte;
				[FieldOffset(0)]
				internal winmdroot.__ushort_8 Word;
			}
		}
	}
}
