// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Storage.FileSystem
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal enum TAPE_POSITION_METHOD
		{
			TAPE_ABSOLUTE_BLOCK = 1,
			TAPE_LOGICAL_BLOCK = 2,
			TAPE_REWIND = 0,
			TAPE_SPACE_END_OF_DATA = 4,
			TAPE_SPACE_FILEMARKS = 6,
			TAPE_SPACE_RELATIVE_BLOCKS = 5,
			TAPE_SPACE_SEQUENTIAL_FMKS = 7,
			TAPE_SPACE_SEQUENTIAL_SMKS = 9,
			TAPE_SPACE_SETMARKS = 8,
		}
	}
}
