// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.SystemInformation
	{
		/// <summary>Describes cache attributes. This structure is used with the GetLogicalProcessorInformationEx function.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-cache_relationship">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct CACHE_RELATIONSHIP
		{
			/// <summary></summary>
			internal byte Level;
			/// <summary>The cache associativity. If this member is CACHE_FULLY_ASSOCIATIVE (0xFF), the cache is fully associative.</summary>
			internal byte Associativity;
			/// <summary>The cache line size, in bytes.</summary>
			internal ushort LineSize;
			/// <summary>The cache size, in bytes.</summary>
			internal uint CacheSize;
			/// <summary>The cache type. This member is a <a href="https://docs.microsoft.com/windows/desktop/api/winnt/ne-winnt-processor_cache_type">PROCESSOR_CACHE_TYPE</a> value.</summary>
			internal winmdroot.System.SystemInformation.PROCESSOR_CACHE_TYPE Type;
			/// <summary>This member is reserved.</summary>
			internal winmdroot.__byte_18 Reserved;
			internal ushort GroupCount;
			internal winmdroot.System.SystemInformation.CACHE_RELATIONSHIP._Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.GROUP_AFFINITY GroupMask;
				[FieldOffset(0)]
				internal winmdroot.System.SystemInformation.__GROUP_AFFINITY_1 GroupMasks;
			}
		}
	}
}
