// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Devices.Display
	{
		/// <summary>The DISPLAYCONFIG_VIDEO_SIGNAL_INFO structure contains information about the video signal for a display.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//wingdi/ns-wingdi-displayconfig_video_signal_info">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct DISPLAYCONFIG_VIDEO_SIGNAL_INFO
		{
			/// <summary>The pixel clock rate.</summary>
			internal ulong pixelRate;
			/// <summary>A <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/ns-wingdi-displayconfig_rational">DISPLAYCONFIG_RATIONAL</a> structure that represents horizontal sync.</summary>
			internal winmdroot.Devices.Display.DISPLAYCONFIG_RATIONAL hSyncFreq;
			/// <summary>A <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/ns-wingdi-displayconfig_rational">DISPLAYCONFIG_RATIONAL</a> structure that represents vertical sync.</summary>
			internal winmdroot.Devices.Display.DISPLAYCONFIG_RATIONAL vSyncFreq;
			/// <summary>A <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/ns-wingdi-displayconfig_2dregion">DISPLAYCONFIG_2DREGION</a> structure that specifies the width and height (in pixels) of the active portion of the video signal.</summary>
			internal winmdroot.Devices.Display.DISPLAYCONFIG_2DREGION activeSize;
			/// <summary>A <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/ns-wingdi-displayconfig_2dregion">DISPLAYCONFIG_2DREGION</a> structure that specifies the width and height (in pixels) of the entire video signal.</summary>
			internal winmdroot.Devices.Display.DISPLAYCONFIG_2DREGION totalSize;
			internal winmdroot.Devices.Display.DISPLAYCONFIG_VIDEO_SIGNAL_INFO._Anonymous_e__Union Anonymous;
			/// <summary>The scan-line ordering (for example, progressive or interlaced) of the video signal. For a list of possible values, see the <a href="https://docs.microsoft.com/windows/desktop/api/wingdi/ne-wingdi-displayconfig_scanline_ordering">DISPLAYCONFIG_SCANLINE_ORDERING</a> enumerated type.</summary>
			internal winmdroot.Devices.Display.DISPLAYCONFIG_SCANLINE_ORDERING scanLineOrdering;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.Devices.Display.DISPLAYCONFIG_VIDEO_SIGNAL_INFO._Anonymous_e__Union._AdditionalSignalInfo_e__Struct AdditionalSignalInfo;
				[FieldOffset(0)]
				internal uint videoStandard;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _AdditionalSignalInfo_e__Struct
				{
					internal uint _bitfield;
				}
			}
		}
	}
}
