// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Controls
	{
		/// <summary>Identifies the pointer device types.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ne-winuser-pointer_device_type">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal enum POINTER_DEVICE_TYPE
		{
			/// <summary>Direct pen digitizer (integrated into display).</summary>
			POINTER_DEVICE_TYPE_INTEGRATED_PEN = 1,
			/// <summary>Indirect pen digitizer (not integrated into display).</summary>
			POINTER_DEVICE_TYPE_EXTERNAL_PEN = 2,
			/// <summary>Touch digitizer.</summary>
			POINTER_DEVICE_TYPE_TOUCH = 3,
			/// <summary>Touchpad digitizer (Windows 8.1 and later).</summary>
			POINTER_DEVICE_TYPE_TOUCH_PAD = 4,
			/// <summary>Forces this enumeration to compile to 32 bits in size. Without this value, some compilers would allow this enumeration to compile to a size other than 32 bits. You should not use this value.</summary>
			POINTER_DEVICE_TYPE_MAX = -1,
		}
	}
}
