// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace UI.Input.Pointer
	{
		/// <summary>Defines the matrix that represents a transform on a message consumer.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winuser/ns-winuser-input_transform">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct INPUT_TRANSFORM
		{
			internal winmdroot.UI.Input.Pointer.INPUT_TRANSFORM._Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal winmdroot.UI.Input.Pointer.INPUT_TRANSFORM._Anonymous_e__Union._Anonymous_e__Struct Anonymous;
				[FieldOffset(0)]
				internal winmdroot.__float_16 m;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _Anonymous_e__Struct
				{
					internal float _11;
					internal float _12;
					internal float _13;
					internal float _14;
					internal float _21;
					internal float _22;
					internal float _23;
					internal float _24;
					internal float _31;
					internal float _32;
					internal float _33;
					internal float _34;
					internal float _41;
					internal float _42;
					internal float _43;
					internal float _44;
				}
			}
		}
	}
}
