// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.ProcessStatus
	{
		/// <summary>Contains information about a page added to a process working set.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//psapi/ns-psapi-psapi_ws_watch_information">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct PSAPI_WS_WATCH_INFORMATION
		{
			/// <summary>A pointer to the instruction that caused the page fault.</summary>
			internal unsafe void* FaultingPc;
			/// <summary>A pointer to the page that was added to the working set.</summary>
			internal unsafe void* FaultingVa;
		}
	}
}
