// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Threading
	{
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct TP_CALLBACK_ENVIRON_V3
		{
			internal uint Version;
			internal winmdroot.System.Threading.PTP_POOL Pool;
			internal nint CleanupGroup;
			internal winmdroot.System.Threading.PTP_CLEANUP_GROUP_CANCEL_CALLBACK CleanupGroupCancelCallback;
			internal unsafe void* RaceDll;
			internal nint ActivationContext;
			internal winmdroot.System.Threading.PTP_SIMPLE_CALLBACK FinalizationCallback;
			internal winmdroot.System.Threading.TP_CALLBACK_ENVIRON_V3._u_e__Union u;
			internal winmdroot.System.Threading.TP_CALLBACK_PRIORITY CallbackPriority;
			internal uint Size;

			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _ACTIVATION_CONTEXT
			{
			}

			[StructLayout(LayoutKind.Explicit)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _u_e__Union
			{
				[FieldOffset(0)]
				internal uint Flags;
				[FieldOffset(0)]
				internal winmdroot.System.Threading.TP_CALLBACK_ENVIRON_V3._u_e__Union._s_e__Struct s;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _s_e__Struct
				{
					internal uint _bitfield;
				}
			}
		}
	}
}
