// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Console
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL PHANDLER_ROUTINE(uint CtrlType);
	}

	namespace System.LibraryLoader
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL ENUMRESLANGPROCW(winmdroot.Foundation.HINSTANCE hModule, winmdroot.Foundation.PCWSTR lpType, winmdroot.Foundation.PCWSTR lpName, ushort wLanguage, nint lParam);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL ENUMRESNAMEPROCW(winmdroot.Foundation.HINSTANCE hModule, winmdroot.Foundation.PCWSTR lpType, winmdroot.Foundation.PWSTR lpName, nint lParam);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL ENUMRESTYPEPROCW(winmdroot.Foundation.HINSTANCE hModule, winmdroot.Foundation.PWSTR lpType, nint lParam);
	}

	namespace System.Memory
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PBAD_MEMORY_CALLBACK_ROUTINE();
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOLEAN PSECURE_MEMORY_CACHE_CALLBACK(void* Addr, nuint Range);
	}

	namespace System.ProcessStatus
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL PENUM_PAGE_FILE_CALLBACKW(void* pContext, winmdroot.System.ProcessStatus.ENUM_PAGE_FILE_INFORMATION* pPageFileInfo, winmdroot.Foundation.PCWSTR lpFilename);
	}

	namespace System.WindowsProgramming
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate uint APPLICATION_RECOVERY_CALLBACK(void* pvParameter);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PIO_APC_ROUTINE(void* ApcContext, winmdroot.System.WindowsProgramming.IO_STATUS_BLOCK* IoStatusBlock, uint Reserved);
	}

	namespace System.Threading
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PFLS_CALLBACK_FUNCTION(void* lpFlsData);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL PINIT_ONCE_FN(winmdroot.System.Threading.RTL_RUN_ONCE* InitOnce, [Optional] void* Parameter, [Optional] void** Context);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTIMERAPCROUTINE([Optional] void* lpArgToCompletionRoutine, uint dwTimerLowValue, uint dwTimerHighValue);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate uint LPTHREAD_START_ROUTINE(void* lpThreadParameter);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void WAITORTIMERCALLBACK(void* param0, winmdroot.Foundation.BOOLEAN param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_SIMPLE_CALLBACK(winmdroot.System.Threading.TP_CALLBACK_INSTANCE* Instance, [Optional] void* Context);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_CLEANUP_GROUP_CANCEL_CALLBACK([Optional] void* ObjectContext, [Optional] void* CleanupContext);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_WORK_CALLBACK(winmdroot.System.Threading.TP_CALLBACK_INSTANCE* Instance, [Optional] void* Context, winmdroot.System.Threading.TP_WORK* Work);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_TIMER_CALLBACK(winmdroot.System.Threading.TP_CALLBACK_INSTANCE* Instance, [Optional] void* Context, winmdroot.System.Threading.TP_TIMER* Timer);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_WAIT_CALLBACK(winmdroot.System.Threading.TP_CALLBACK_INSTANCE* Instance, [Optional] void* Context, winmdroot.System.Threading.TP_WAIT* Wait, uint WaitResult);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PTP_WIN32_IO_CALLBACK(winmdroot.System.Threading.TP_CALLBACK_INSTANCE* Instance, [Optional] void* Context, [Optional] void* Overlapped, uint IoResult, nuint NumberOfBytesTransferred, winmdroot.System.Threading.TP_IO* Io);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void LPFIBER_START_ROUTINE(void* lpFiberParameter);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PRTL_UMS_SCHEDULER_ENTRY_POINT(winmdroot.System.SystemServices.RTL_UMS_SCHEDULER_REASON Reason, nuint ActivationPayload, void* SchedulerParam);
	}

	namespace Foundation
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void PAPCFUNC(nuint Parameter);
	}

	namespace System.IO
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void LPOVERLAPPED_COMPLETION_ROUTINE(uint dwErrorCode, uint dwNumberOfBytesTransfered, global::System.Threading.NativeOverlapped* lpOverlapped);
	}

	namespace System.SetupAndMigration
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void OOBE_COMPLETED_CALLBACK([Optional] void* CallbackContext);
	}

	namespace Storage.FileSystem
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate uint LPPROGRESS_ROUTINE(long TotalFileSize, long TotalBytesTransferred, long StreamSize, long StreamBytesTransferred, uint dwStreamNumber, winmdroot.Storage.FileSystem.LPPROGRESS_ROUTINE_CALLBACK_REASON dwCallbackReason, winmdroot.Foundation.HANDLE hSourceFile, winmdroot.Foundation.HANDLE hDestinationFile, [Optional] void* lpData);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Storage.FileSystem.COPYFILE2_MESSAGE_ACTION PCOPYFILE2_PROGRESS_ROUTINE(winmdroot.Storage.FileSystem.COPYFILE2_MESSAGE* pMessage, [Optional] void* pvCallbackContext);
	}

	namespace Globalization
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL CALINFO_ENUMPROCW(winmdroot.Foundation.PWSTR param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL CALINFO_ENUMPROCEXW(winmdroot.Foundation.PWSTR param0, uint param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL TIMEFMT_ENUMPROCW(winmdroot.Foundation.PWSTR param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL DATEFMT_ENUMPROCW(winmdroot.Foundation.PWSTR param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL DATEFMT_ENUMPROCEXW(winmdroot.Foundation.PWSTR param0, uint param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL GEO_ENUMPROC(int param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL GEO_ENUMNAMEPROC(winmdroot.Foundation.PWSTR param0, winmdroot.Foundation.LPARAM param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL LOCALE_ENUMPROCW(winmdroot.Foundation.PWSTR param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL LANGUAGEGROUP_ENUMPROCW(uint param0, winmdroot.Foundation.PWSTR param1, winmdroot.Foundation.PWSTR param2, uint param3, nint param4);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL LANGGROUPLOCALE_ENUMPROCW(uint param0, uint param1, winmdroot.Foundation.PWSTR param2, nint param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL UILANGUAGE_ENUMPROCW(winmdroot.Foundation.PWSTR param0, nint param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL CODEPAGE_ENUMPROCW(winmdroot.Foundation.PWSTR param0);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL CALINFO_ENUMPROCEXEX(winmdroot.Foundation.PWSTR param0, uint param1, winmdroot.Foundation.PWSTR param2, winmdroot.Foundation.LPARAM param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL DATEFMT_ENUMPROCEXEX(winmdroot.Foundation.PWSTR param0, uint param1, winmdroot.Foundation.LPARAM param2);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL TIMEFMT_ENUMPROCEX(winmdroot.Foundation.PWSTR param0, winmdroot.Foundation.LPARAM param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL LOCALE_ENUMPROCEX(winmdroot.Foundation.PWSTR param0, uint param1, winmdroot.Foundation.LPARAM param2);
	}

	namespace System.DataExchange
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.System.DataExchange.HDDEDATA PFNCALLBACK(uint wType, uint wFmt, winmdroot.System.DataExchange.HCONV hConv, winmdroot.System.DataExchange.HSZ hsz1, winmdroot.System.DataExchange.HSZ hsz2, winmdroot.System.DataExchange.HDDEDATA hData, nuint dwData1, nuint dwData2);
	}

	namespace System.StationsAndDesktops
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL DESKTOPENUMPROCW(winmdroot.Foundation.PWSTR param0, winmdroot.Foundation.LPARAM param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL WINSTAENUMPROCW(winmdroot.Foundation.PWSTR param0, winmdroot.Foundation.LPARAM param1);
	}

	namespace UI.WindowsAndMessaging
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL WNDENUMPROC(winmdroot.Foundation.HWND param0, winmdroot.Foundation.LPARAM param1);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void SENDASYNCPROC(winmdroot.Foundation.HWND param0, uint param1, nuint param2, winmdroot.Foundation.LRESULT param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.LRESULT WNDPROC(winmdroot.Foundation.HWND param0, uint param1, winmdroot.Foundation.WPARAM param2, winmdroot.Foundation.LPARAM param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate nint DLGPROC(winmdroot.Foundation.HWND param0, uint param1, winmdroot.Foundation.WPARAM param2, winmdroot.Foundation.LPARAM param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void TIMERPROC(winmdroot.Foundation.HWND param0, uint param1, nuint param2, uint param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL PROPENUMPROCEXW(winmdroot.Foundation.HWND param0, winmdroot.Foundation.PWSTR param1, winmdroot.Foundation.HANDLE param2, nuint param3);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL PROPENUMPROCW(winmdroot.Foundation.HWND param0, winmdroot.Foundation.PCWSTR param1, winmdroot.Foundation.HANDLE param2);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void MSGBOXCALLBACK(winmdroot.UI.Shell.HELPINFO* lpHelpInfo);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.LRESULT HOOKPROC(int code, winmdroot.Foundation.WPARAM wParam, winmdroot.Foundation.LPARAM lParam);
	}

	namespace UI.Accessibility
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate void WINEVENTPROC(winmdroot.UI.Accessibility.HWINEVENTHOOK hWinEventHook, uint @event, winmdroot.Foundation.HWND hwnd, int idObject, int idChild, uint idEventThread, uint dwmsEventTime);
	}

	namespace Graphics.Gdi
	{
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL GRAYSTRINGPROC(winmdroot.Graphics.Gdi.HDC param0, winmdroot.Foundation.LPARAM param1, int param2);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL DRAWSTATEPROC(winmdroot.Graphics.Gdi.HDC hdc, winmdroot.Foundation.LPARAM lData, winmdroot.Foundation.WPARAM wData, int cx, int cy);
		[UnmanagedFunctionPointerAttribute(CallingConvention.Winapi)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal unsafe delegate winmdroot.Foundation.BOOL MONITORENUMPROC(winmdroot.Graphics.Gdi.HMONITOR param0, winmdroot.Graphics.Gdi.HDC param1, winmdroot.Foundation.RECT* param2, winmdroot.Foundation.LPARAM param3);
	}
}
