// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Storage.Packaging.Appx
	{
		/// <summary>Represents package identification information, such as name, version, and publisher.</summary>
		/// <remarks>
		/// <para>For info about string size limits, see <a href="https://docs.microsoft.com/windows/desktop/appxpkg/identity-constants">Identity constants</a>.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[StructLayout(LayoutKind.Sequential, Pack = 4)]
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct PACKAGE_ID
		{
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT32</a></b> Reserved; do not use.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint reserved;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">UINT32</a></b> The processor architecture of the package. This member must be one of the values of the <b>PROCESSOR_ARCHITECTURE_...</b> constants that matches the <b><a href="https://docs.microsoft.com/uwp/api/Windows.System.ProcessorArchitecture">ProcessorArchitecture</b> enumeration</a> values. This includes: * PROCESSOR_ARCHITECTURE_AMD64 * PROCESSOR_ARCHITECTURE_ARM * PROCESSOR_ARCHITECTURE_ARM64 * PROCESSOR_ARCHITECTURE_INTEL * PROCESSOR_ARCHITECTURE_IA32_ON_ARM64 * PROCESSOR_ARCHITECTURE_NEUTRAL * PROCESSOR_ARCHITECTURE_UNKNOWN</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal uint processorArchitecture;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/api/appmodel/ns-appmodel-package_version">PACKAGE_VERSION</a></b> The version of the package.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Storage.Packaging.Appx.PACKAGE_VERSION version;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">PWSTR</a></b> The name of the package.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Foundation.PWSTR name;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">PWSTR</a></b> The publisher of the package. If there is no publisher for the package, this member is <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Foundation.PWSTR publisher;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">PWSTR</a></b> The resource identifier (ID) of the package. If there is no resource ID for the package, this member is <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Foundation.PWSTR resourceId;
			/// <summary>
			/// <para>Type: <b><a href="https://docs.microsoft.com/windows/desktop/WinProg/windows-data-types">PWSTR</a></b> The publisher identifier (ID) of the package. If there is no publisher ID for the package, this member is <b>NULL</b>.</para>
			/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_id#members">Read more on docs.microsoft.com</see>.</para>
			/// </summary>
			internal winmdroot.Foundation.PWSTR publisherId;
		}
	}
}
