// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace System.Diagnostics.Debug
	{
		/// <summary>Represents a context frame on WOW64.</summary>
		/// <remarks>
		/// <para>In the following versions of Windows, Slot 1 of Thread Local Storage (TLS) holds a pointer to a structure that contains a <b>WOW64_CONTEXT</b> structure starting at offset 4. This might change in later versions of Windows. </para>
		/// <para>This doc was truncated.</para>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//winnt/ns-winnt-wow64_context#">Read more on docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct WOW64_CONTEXT
		{
			internal uint ContextFlags;
			internal uint Dr0;
			internal uint Dr1;
			internal uint Dr2;
			internal uint Dr3;
			internal uint Dr6;
			internal uint Dr7;
			internal winmdroot.System.Diagnostics.Debug.WOW64_FLOATING_SAVE_AREA FloatSave;
			internal uint SegGs;
			internal uint SegFs;
			internal uint SegEs;
			internal uint SegDs;
			internal uint Edi;
			internal uint Esi;
			internal uint Ebx;
			internal uint Edx;
			internal uint Ecx;
			internal uint Eax;
			internal uint Ebp;
			internal uint Eip;
			internal uint SegCs;
			internal uint EFlags;
			internal uint Esp;
			internal uint SegSs;
			internal winmdroot.__byte_512 ExtendedRegisters;
		}
	}
}
