// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

#pragma warning disable CS1591,CS1573,CS0465,CS0649,CS8019,CS1570,CS1584,CS1658,CS0436,CS8981
using global::System;
using global::System.Diagnostics;
using global::System.Diagnostics.CodeAnalysis;
using global::System.Runtime.CompilerServices;
using global::System.Runtime.InteropServices;
using global::System.Runtime.Versioning;
using winmdroot = global::Windows.Win32;
namespace Windows.Win32
{
	namespace Storage.Packaging.Appx
	{
		/// <summary>Represents the package version information.</summary>
		/// <remarks>
		/// <para><see href="https://docs.microsoft.com/windows/win32/api//appmodel/ns-appmodel-package_version">Learn more about this API from docs.microsoft.com</see>.</para>
		/// </remarks>
		[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
		internal partial struct PACKAGE_VERSION
		{
			internal winmdroot.Storage.Packaging.Appx.PACKAGE_VERSION._Anonymous_e__Union Anonymous;

			[StructLayout(LayoutKind.Explicit, Pack = 4)]
			[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
			internal partial struct _Anonymous_e__Union
			{
				[FieldOffset(0)]
				internal ulong Version;
				[FieldOffset(0)]
				internal winmdroot.Storage.Packaging.Appx.PACKAGE_VERSION._Anonymous_e__Union._Anonymous_e__Struct Anonymous;

				[global::System.CodeDom.Compiler.GeneratedCode("Microsoft.Windows.CsWin32", "0.2.104-beta+6d86f35b75")]
				internal partial struct _Anonymous_e__Struct
				{
					internal ushort Revision;
					internal ushort Build;
					internal ushort Minor;
					internal ushort Major;
				}
			}
		}
	}
}
